### ISSUE TITLE
New Error for updated image. No longer able to acess webgui

### ISSUE THREAD

**Issue by SC8198** [Thomas-Philippot/removarr#16]
I pulled the new image and a new error has appeared.

Listening on http://0.0.0.0:3000
(node:1) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by Thomas-Philippot** [comment]
Hi, this warning is triggered by the [plex-api](https://github.com/phillipj/node-plex-api) package that I use to fetch the admin libraries.

Did you restarted the container with `docker compose up -d` again ? maybe try with the `--build` and  `--force-recreate` flags.

I just pushed a smaller image and it seems to be running just fine.

feel free to share you `compose.yaml` file if the web ui is still not available after that

**Comment by bobvmierlo** [comment]
I have the same issue on a fresh installed instance using the docker compose yaml below.

```yaml
services:
  removarr:
    container_name: removarr
    image: tphilippot/removarr:latest
    ports:
      - 3001:3000
    volumes:
      - ./config:/app/config
```

```
(node:1) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
